### ISSUE TITLE
Could not find coffee command

### ISSUE THREAD

**Issue by davewhitley** [trello/iconathon#1]
```
[nodemon] starting `coffee app.coffee`
sh: coffee: command not found
[nodemon] failed to start process, "coffee" exec not found
events.js:146
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (127)
    at emit (events.js:144:17)
    at ChildProcess.<anonymous> (/Users/User/iconathon/node_modules/nodemon/lib/monitor/run.js:116:11)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
Daves-Laptop:iconathon User$ [17:22:40] Requiring external module coffee-script/register
```

Anyone else get this issue?

All packages were installed successfully afaik

**Comment by davewhitley** [comment]
This was fixed by installing coffee script 

`npm install -g coffee-script`

Please update the docs!

**Comment by nysthee** [comment]
You can propose a doc improvement yourself by making a PR. :smile:

**Comment by bobbygrace** [comment]
@drw158 I needed the call the local coffeescript dependency. I pushed an update. Sorry about the delay!
